# Default values for cellery-runtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  celleryRuntime:
      db:
        carbon:
          username: "celleryDbUser"
          password: "celleryDBPassword"

      carbon:
        admin:
          username: "celleryRuntimeUser"
          password: "celleryRuntimePassword"

mysql:
  enabled: true
  rootPassword: "mysqlRootPass"

  # NFS server
  nfs:
    enabled: false
    serverIp: 10.163.138.18
    shareLocation: "/data"

apim:
  enabled: false
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      ingress.kubernetes.io/ssl-redirect: "true"
      certmanager.k8s.io/cluster-issuer: "letsencrypt-dev"
    hosts:
    - host: apim
      paths: ["/"]
    tls:
    - secretName: apim-tls
      hosts:
      - apim

idp:
  enabled: false
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      ingress.kubernetes.io/ssl-redirect: "true"
      certmanager.k8s.io/cluster-issuer: "letsencrypt-dev"
    hosts:
    - host: idp
      paths: ["/"]
    tls:
    - secretName: idp-tls
      hosts:
      - idp

observability-portal:
    enabled: true

sp-worker:
    enabled: true
