# Copyright (c) 2019, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for cellery-runtime.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  celleryRuntime:
      db:
        host: "cellery-runtime-mysql"
        carbon:
          username: "celleryDbUser"
          password: "celleryDBPassword"

      carbon:
        admin:
          username: "celleryRuntimeUser"
          password: "celleryRuntimePassword"

mysql:
  enabled: false
  rootPassword: "mysqlRootPass"

  ## Persist data to a persistent volume
  persistence:
    enabled: false
    ## database data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: "local-storage"
    accessMode: ReadWriteOnce
    size: 10Gi
    subPath: cellery_runtime_mysql
    annotations: {}

  # NFS server
  nfs:
    enabled: false
    serverIp: 10.163.138.18
    shareLocation: "/data"

  localStorage:
    enabled: false
    storagePath: "/var/tmp/cellery/mysql"


controller:
  enabled: false

apim:
  enabled: false

  datasources:
    enabled: true

  deployment:
    enabled: true

  persistence:
    enabled: false
    media: "local-filesystem"  #default value "volatile" "local-filesystem" or "nfs"
    nfsServerIp: 192.168.100.10
    sharedDeploymentLocation: "/data"

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "route"
      nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    hosts:
    - host: wso2-apim
      paths: ["/"]
    tls:
    - secretName: apim-tls
      hosts:
      - wso2-apim

idp:
  enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "route"
      nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    hosts:
    - host: idp.cellery-system
      paths: ["/"]
    tls:
    - secretName: idp-tls
      hosts:
      - idp.cellery-system

observability-agent:
  enabled: false

sp:
  enabled: false

  datasources:
    enabled: true

    deployment:
      enabled: true

grafana:
  enabled: false

prometheus:
  enabled: false

portal:
  enabled: false
