apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.mesh.cellery.io
spec:
  group: mesh.cellery.io
  version: v1alpha2
  scope: Namespaced
  names:
    kind: Component
    plural: components
    singular: component
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Type
    type: string
    description: Type of this component
    JSONPath: .status.componentType
  - name: Status
    type: string
    description: Status of this component
    JSONPath: .status.status
  - name: Service-Name
    type: string
    description: Service name of this component
    JSONPath: .status.serviceName
  - name: Ready-Replicas
    type: integer
    description: Number of replicas available for this component
    JSONPath: .status.availableReplicas
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
