apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: cellery-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: wso2cellery/mesh-controller:0.6.0
      serviceAccountName: controller
