apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cells.mesh.cellery.io
spec:
  group: mesh.cellery.io
  version: v1alpha2
  scope: Namespaced
  names:
    kind: Cell
    plural: cells
    singular: cell
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Status
    type: string
    description: Status of this cell
    JSONPath: .status.status
  - name: Gateway
    type: string
    description: Gateway service name of this cell
    JSONPath: .status.gatewayServiceName
  - name: Total-Components
    type: integer
    description: Number of components in this cell
    JSONPath: .status.componentCount
  - name: Active-Components
    type: integer
    description: Number of active components in this cell
    JSONPath: .status.activeComponentCount
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
