apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.mesh.cellery.io
spec:
  group: mesh.cellery.io
  version: v1alpha2
  scope: Namespaced
  names:
    kind: Gateway
    plural: gateways
    singular: gateway
    shortNames:
    - cgateways
    - cgw
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.status
  - name: Service-Name
    type: string
    description: Service name of this gateway
    JSONPath: .status.serviceName
  - name: Ready-Replicas
    type: integer
    description: Number of replicas available for this gateway
    JSONPath: .status.availableReplicas
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
