apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: telepresence
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: telepresence
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: telepresence
        image: datawire/telepresence-k8s:0.101
